---
title: "실험계획법 hw4"
author: "2019150418 통계학과 김나연"
date: '2021 5 31 '
output: word_document
---

# 8.3
```{r}
A=c(0,0,0,1,1,1,0,0,0,1,1,1,0,0,0,1,1,1,0,0,0,1,1,1,0,0,0,1,1,1,0,0,0,1,1,1,0,0,0,1,1,1,0,0,0,1,1,1)
B=c(0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1)
C=c(rep(0,12),rep(1,12),rep(0,12),rep(1,12))
D=c(0,0,0,1,1,1,1,1,1,0,0,0,1,1,1,0,0,0,0,0,0,1,1,1,0,0,0,1,1,1,1,1,1,0,0,0,1,1,1,0,0,0,0,0,0,1,1,1)
E=c(rep(0,24),rep(1,24))
rep=rep(c(1,2,3),time=16)
y=c(7.78,7.78,7.81,8.15,8.18,7.88,7.5,7.56,7.5,7.59,7.56,7.5,7.54,8,7.88,7.69,8.09,8.06,7.56,7.52,7.44,7.56,7.81,7.69,7.5,7.25,7.12,7.88,7.88,7.44,7.5,7.56,7.5,7.63,7.75,7.56,7.32,7.44,7.45,7.56,7.69,7.62,7.18,7.23,7.25,7.81,7.5,7.59)

q8.3=data.frame(A,B,C,D,E,rep,y)
attach(q8.3)
A=as.factor(A)
B=as.factor(B)
C=as.factor(C)
D=as.factor(D)
E=as.factor(E)
rep=as.factor(rep)
fit1=aov(y~A+B+C+D+E)
fit2=aov(y~A+B+C+D+E+A:B+A:C+A:D+A:E+B:C+B:D+B:E+C:D+C:E+D:E)
fit3=aov(y~rep+A+B+C+D+E+A:B+A:C+A:D+A:E+B:C+B:D+B:E+C:D+C:E+D:E)
summary(fit1)
summary(fit2)
summary(fit3)
```

# 9.2

(1)






(2)
```{r}
humidity=rep(c(50,70,90),4)
strips=rep(1:2,each=3,time=2)
rep=rep(1:2,each=6)
y=c(1.12,3.50,1.00,1.13,0.75,0.50,1.75,1.75,1.50,5.25,1.62,1.50)
q9.2=data.frame(rep,humidity,strips,y)

humidity=as.factor(humidity)
strips=as.factor(strips)
rep=as.factor(rep)

md1=aov(y~rep+humidity*strips+Error(rep:humidity))
summary(md1) # 반복이 유의하지 않으므로 error term으로 풀링하여 모델 설정

md2=aov(y~humidity+humidity*strips+Error(humidity/rep))
summary(md2)
```

(3)











# 9.4
(1) 







(2)
```{r}
irrigation=rep(c('Control','Irrigated'),each=3,time=12)
density=rep(c('high','low','medium'),each=6,time=4)
fertilizer=rep(c('N','NP','P'),time=24)
rep=rep(c('A','B','C','D'),each=18)
y=c(81,93,92,78,122,98,
    90,107,95,80,100,87,
    92,92,89,121,119,110,
    74,74,81,136,132,133,
    83,95,80,102,105,109,
    98,106,98,99,123,94,
    82,94,78,119,136,122,
    85,88,88,60,114,104,
    112,91,104,90,113,118,
    85,83,89,116,133,136,
    86,89,78,73,114,114,
    79,87,86,109,126,131)

q9.4=data.frame(rep,irrigation,density,fertilizer,y)
rep=as.factor(rep)
irrigation=as.factor(irrigation)
density=as.factor(density)
fertilizer=as.factor(fertilizer)

md1=aov(y~irrigation*fertilizer*density+Error(rep/irrigation/density/fertilizer))
summary(md1)
```


