---
title: "실계 hw2"
author: "2019150418 통계학과 김나연"
date: '2021 4 17 '
output: word_document
---

```{r}
# 4.2
trt=c(rep(1:5,3))
block=c(rep(1,5),rep(2,5),rep(3,5))
al=c(175,95,180,170,155,190,185,180,200,190,185,165,175,195,200)
trt=as.factor(trt)
block=as.factor(block)
df4_2=data.frame(trt,block,al)
attach(df4_2)

## (2)
tapply(al,trt,mean)
tapply(al,trt,sd)

## (3)
boxplot(al~trt)
boxplot(al~block)

## (4)
aov4_2=aov(al~trt+block)
summary(aov4_2)


## (7)
lsd4_2=pairwise.t.test(al,trt,p.adjust='none')
lsd4_2
```

```{r}
# 4.4
trt=c(rep(1,5),rep(1.5,5),rep(2,5),rep(2.5,5))
block=c(rep(1:5,4))
eft=c(10,6,6,6,7,7,6,6,1,6,5,3,4,2,5,6,4,3,2,5)
trt=as.factor(trt)
block=as.factor(block)

## (2)
tapply(eft,trt,mean)
tapply(eft,trt,sd)

## (3)
boxplot(eft~trt)
boxplot(eft~block)

## (4)
aov4_4=aov(eft~trt+block)
summary(aov4_4)

## (7)
lsd4_4=pairwise.t.test(eft,trt,p.adjust='none')
lsd4_4
```

```{r}
# 4.7
trt=c(rep(2,3),rep(4,3),rep(6,3),rep(8,3),rep(10,3),rep(12,3),rep(14,3))
block=c(1,5,7,1,2,6,2,3,7,1,3,4,2,4,5,3,5,6,4,6,7)
count=c(114,120,117,126,120,119,137,117,134,141,129,149,145,148,145,120,118,124,140,130,140)
df4_7=data.frame(trt,block,count)
attach(df4_7)
trt=as.factor(trt)
block=as.factor(block)

## (2)
tapply(count,trt,mean)
tapply(count,trt,sd)

## (3)
plot(count~trt)

## (4)
aov4_7.a=aov(count~block+trt) # adjusted treatment
aov4_7.b=aov(count~trt+block) # adjusted block
summary(aov4_7.a)
summary(aov4_7.b)
```

```{r}
# 5.1
num=c(rep(1,5),rep(2,5),rep(3,5),rep(4,5),rep(5,5))
car_type=c(rep(c(1,2,3,4,5),5))
company=c('A','B','C','D','E','E','A','B','C','D','D','E','A','B','C','C','D','E','A','B','B','C','D','E','A')
tire=c(26,19,28,29,20,21,23,20,24,29,29,22,23,20,24,28,28,20,28,15,17,28,23,20,25)
df5.1=data.frame(num,car_type,company,tire)
attach(df5.1)
num=as.factor(df5.1$num);car_type=as.factor(df5.1$car_type);company=as.factor(df5.1$company)

## (2)
by(tire,company,function(x){c(mean(x),sd(x))})

## (3)
by(tire,car_type,function(x){c(mean(x),sd(x))})  

## (4)
by(tire,num,function(x){c(mean(x),sd(x))})   

## (5)
lm5.1=lm(tire~car_type+num+company)  
anova5.1=anova(lm5.1)
anova5.1

## (9)
pairwise.t.test(tire,company,p.adjust='none')
```

```{r}
# 라틴방격법 1번
driver=c(rep('B1',4),rep('B2',4),rep('B3',4),rep('B4',4)) # 행
company=c(rep(c('A1','A2','A3','A4'),4)) # 열
road=c('C3','C4','C1','C2','C2','C3','C4','C1','C1','C2','C3','C4','C4','C1','C2','C3') # 처리
tear=c(7,6,8,3,9,7,6,8,12,9,5,4,8,9,8,4)
df1=data.frame(driver,company,road,tear)
attach(df1)
driver=as.factor(driver)
company=as.factor(company)
road=as.factor(road)

## (1)
lm1=lm(tear~driver+company+road)
aov1=anova(lm1)
aov1

## (2)
by(tear,company,function(x){mean(x)})
int=qt(0.975,6)*sqrt(0.8958/4)
lower=c(9-int,7.75-int,6.75-int,4.75-int)
upper=c(9+int,7.75+int,6.75+int,4.75+int)
y..kbar=c(9,7.75,6.75,4.75)
company_f=c('A1','A2','A3','A4')
conf_interval=data.frame(company_f,lower,upper,y..kbar)
conf_interval
library(dplyr)
library(ggplot2)
conf_interval%>%ggplot(aes(company_f,y..kbar))+geom_point()+geom_errorbar(aes(ymin=lower,ymax=upper)) # A(col)인자는 4일 때 가장 작아짐


## (3)
by(tear,road,function(x){mean(x)})
lower=c(9.25-2.45,7.25-2.45,5.75-2.45,6-2.45)
upper=c(9.25+2.45,7.25+2.45,5.75+2.45,6+2.45)
yi..bar=c(9.25,7.25,5.75,6)
road=c('C1','C2','C3','C4')
conf_interval=data.frame(road,lower,upper,yi..bar)
conf_interval%>%ggplot(aes(road,yi..bar))+geom_point()+geom_errorbar(aes(ymin=lower,ymax=upper)) # C인자는 C3일 때 가장 작아짐

c(yi..bar[3]+y..kbar[4]-mean(tear)-qt(0.975,6)*sqrt(7*0.9/16),yi..bar[3]+y..kbar[4]-mean(tear)+qt(0.975,6)*sqrt(7*0.9/16))
```
```{r}
# 라틴방격법 3번
row=c(rep('B1',4),rep('B2',4),rep('B3',4),rep('B4',4))
col=c(rep(c('A1','A2','A3','A4'),4))
trt1=c('C1','C2','C3','C4','C2','C1','C4','C3','C3','C4','C1','C2','C4','C3','C2','C1')
trt2=c('D1','D3','D4','D2','D2','D4','D3','D1','D3','D1','D2','D4','D4','D2','D1','D3')
count=c(49,38,48,38,40,53,33,54,42,45,53,54,42,40,41,40)
df3=data.frame(row,col,trt1,trt2,count)
attach(df3)
row=as.factor(row);col=as.factor(col);trt1=as.factor(trt1);trt2=as.factor(trt2)

## (1)
fit3=lm(count~.,data=df3)
anova(fit3)

## (2)
by(count,row,function(x){mean(x)})
int=qt(0.975,3)*sqrt(10.417/4)
lower=c(43.25-int,45-int,48.5-int,40.75-int)
upper=c(43.25+int,45+int,48.5+int,40.75+int)
y.j..bar=c(43.25,45,48.5,40.75)
row_f=c('B1','B2','B3','B4')
conf_interval=data.frame(row_f,lower,upper,y.j..bar)
conf_interval%>%ggplot(aes(row_f,y.j..bar))+geom_point()+geom_errorbar(aes(ymin=lower,ymax=upper)) # row요인이 3일 때

by(count,col,function(x){mean(x)})
int=qt(0.975,3)*sqrt(10.417/4)
lower=c(43.25-int,44-int,43.75-int,46.5-int)
upper=c(43.25+int,44+int,43.75+int,46.5+int)
y..k.bar=c(43.25,44,43.75,46.5)
col_f=c('A1','A2','A3','A4')
conf_interval=data.frame(col_f,lower,upper,y..k.bar)
conf_interval%>%ggplot(aes(col_f,y..k.bar))+geom_point()+geom_errorbar(aes(ymin=lower,ymax=upper)) # col 요인이 4일 때

by(count,trt1,function(x){mean(x)})
int=qt(0.975,3)*sqrt(10.417/4)
lower=c(48.75-int,43.25-int,46-int,39.5-int)
upper=c(48.75+int,43.25+int,46+int,39.5+int)
yi...bar=c(48.75,43.25,46,39.5)
trt1_f=c('C1','C2','C3','C4')
conf_interval=data.frame(trt1_f,lower,upper,yi...bar)
conf_interval%>%ggplot(aes(trt1_f,yi...bar))+geom_point()+geom_errorbar(aes(ymin=lower,ymax=upper)) # trt1 요인이 1일 때

by(count,trt2,function(x){mean(x)})
int=qt(0.975,3)*sqrt(10.417/4)
lower=c(47.25-int,42.75-int,38.25-int,49.25-int)
upper=c(47.25+int,42.75+int,38.25+int,49.25+int)
y...lbar=c(47.25,42.75,38.25,49.25)
trt2_f=c('D1','D2','D3','D4')
conf_interval=data.frame(trt2_f,lower,upper,y...lbar)
conf_interval%>%ggplot(aes(trt2_f,y...lbar))+geom_point()+geom_errorbar(aes(ymin=lower,ymax=upper)) # trt2 요인이 4일 때

c((yi...bar[1]+y.j..bar[3]+y..k.bar[4]+y...lbar[4]-3*mean(count))-qt(0.975,3)*sqrt(10.42*13/16),(yi...bar[1]+y.j..bar[3]+y..k.bar[4]+y...lbar[4]-3*mean(count))+qt(0.975,3)*sqrt(10.42*13/16))

```

